### ISSUE TITLE
@formatjs/cli@npm:4.2.6 doesn't provide vue, requested by @vue/compiler-sfc

### ISSUE THREAD

**Issue by lensbart** [formatjs/formatjs#2817]
## Which package?
@formatjs/cli@4.2.6

## Describe the bug
See title: Yarn 2 is a bit more strict regarding dependency resolution. In this case, `@vue/compiler-sfc` has `vue` [listed in its peerDependencies](https://github.com/vuejs/vue-next/blob/master/packages/compiler-sfc/package.json) so it should be supplied by packages that depend on it, such as `@formatjs/cli`.

## To Reproduce
- Use yarn 
- `yarn set version berry`
- `yarn add @formatjs/cli`

## Expected behavior
No warning when running `yarn install`

**Comment by lensbart** [comment]
The warning can be suppressed by adding the following to `.yarnrc.yml`:

```yml
packageExtensions:
  # awaiting fix: https://github.com/formatjs/formatjs/issues/2817
  '@vue/compiler-sfc@*':
    peerDependenciesMeta:
      vue:
        optional: true
```
