### ISSUE TITLE
Fix dependencies

### ISSUE THREAD

**Issue by lensbart** [formatjs/formatjs#3173]
Several warnings come up when using Yarn (`yarn set version latest`)

* `@formatjs/intl-locale@npm:2.4.37` doesn't provide `@types/node`, requested by `@formatjs/intl-getcanonicallocales`
* `babel-plugin-formatjs@npm:10.3.8` doesn't provide `@types/node`, requested by `@formatjs/ts-transformer`
* `@formatjs/cli@npm:4.2.33` doesn't provide `vue`, requested by `@vue/compiler-sfc`
* `babel-plugin-formatjs@npm:10.3.8` doesn't provide `typescript`, requested by `@formatjs/ts-transformer`
* `eslint-plugin-formatjs@npm:2.17.6` doesn't provide `@types/node`, requested by `@formatjs/ts-transformer`
* `react-intl@npm:5.20.10` doesn't provide `@types/node`, requested by `@formatjs/intl`

These can be suppressed by including the following in `.yarnrc.yml`

```yml
packageExtensions:
  # awaiting fix: https://github.com/formatjs/formatjs/issues/3173
  '@formatjs/intl-locale@*':
    peerDependencies:
      '@types/node': '*'

  '@formatjs/cli@*':
    peerDependencies:
      vue: '*'

  'babel-plugin-formatjs@*':
    peerDependencies:
      '@types/node': '*'
      'typescript': '*'

  'eslint-plugin-formatjs@*':
    peerDependencies:
      '@types/node': '*'

  react-intl@*:
    peerDependencies:
      '@types/node': '*'
```

But they should be fixed by including
* `@types/node` as a dependency in the `package.json` file of  `@formatjs/intl-locale`, `babel-plugin-formatjs`, `eslint-plugin-formatjs`, `react-intl`
* `typescript` as a dependency in `babel-plugin-formatjs`
* `vue` as a dependency of `@formatjs/cli`

Have a nice day!

**Comment by glen-84** [comment]
I think the `@vue/compiler-*` packages should be optional peer dependencies of `@formatjs/cli`.

I'm using Vue, but not everyone else is.

**Comment by longlho** [comment]
we used to declare vue stuff as peer dep then people complain about the `WARN`. It's gone kinda full circle.

**Comment by lensbart** [comment]
In that case, the proper way to resolve this issue would be to

* leverage the [`peerDependenciesMeta`](https://docs.npmjs.com/cli/v7/configuring-npm/package-json#peerdependenciesmeta) setting to mark the “vue stuff” peer dependencies as optional in `@formatjs/cli`, which they are. This way, there won’t be a warning and people likely won’t complain
* fix the dependencies mismatch between the other packages regarding `@types/node` and `typescript`. In all of these cases, both the “requesting” package and the “providing” package are defined in this repository.

**Comment by glen-84** [comment]
> we used to declare vue stuff as peer dep then people complain about the `WARN`. It's gone kinda full circle.

@longlho Which warning are you referring to? Optional peer dependencies shouldn't result in any warnings.

**Comment by longlho** [comment]
So to be clear the vue stuff in `@formatjs/cli` are NOT `peerDependencies`. We have code that directly import them and we don't test/guard import restriction on certain code path so non-vue extractor doesn't `import` vue.

The `@types/node` stuff should be fixed in the latest version.

**Comment by lensbart** [comment]
> So to be clear the vue stuff in `@formatjs/cli` are NOT `peerDependencies`. We have code that directly import them and we don't test/guard import restriction on certain code path so non-vue extractor doesn't `import` vue.

I think the proper approach, then, is to set `optional: true` on the [`peerDependenciesMeta` field](https://docs.npmjs.com/cli/v7/configuring-npm/package-json#peerdependenciesmeta) for the corresponding dependencies.

**Comment by longlho** [comment]
but it's not a peerDependency

**Comment by lensbart** [comment]
It seems like most of the issues are resolved. Thank you!

However, one warning remains when running `yarn`:
```
➤ YN0002: │ @formatjs/intl-locale@npm:2.4.45 doesn't provide @types/node (p02c46), requested by @formatjs/intl-getcanonicallocales
```

Which can be muted by adding the following in `.yarnrc.yml`:
```yaml
packageExtensions:
  # awaiting fix: https://github.com/formatjs/formatjs/issues/3173
  '@formatjs/intl-locale@*':
    peerDependencies:
      '@types/node': '*'
```

Or should I file a separate issue?

Thanks!
