### ISSUE TITLE
Add `@types/node` dependency

### ISSUE THREAD

**Issue by lensbart** [formatjs/formatjs#3474]
When running `yarn` I get the following warning:

```
➤ YN0002: │ @formatjs/intl-locale@npm:2.4.45 doesn't provide @types/node (p02c46), requested by @formatjs/intl-getcanonicallocales
```

Which can be muted by adding the following in `.yarnrc.yml`:
```yaml
packageExtensions:
  # awaiting fix: https://github.com/formatjs/formatjs/issues/3173
  '@formatjs/intl-locale@*':
    peerDependencies:
      '@types/node': '*'
```

But should be fixedby adding `@types/node` as a dependency to `@formatjs/intl-locale`

Thanks!
