### ISSUE TITLE
`@formatjs/cli` is missing a dependency on `fs-extra`

### ISSUE THREAD

**Issue by nstepien** [formatjs/formatjs#3625]
## Which package?
Since this is a monorepo. Please specify which package this bug report is for.

`@formatjs/cli@5.0.1`

## Describe the bug

I'm trying to use the `@formatjs/cli` package and I run into an import crash:
```
node:internal/modules/cjs/loader:939
  const err = new Error(message);
              ^

Error: Cannot find module 'fs-extra'
Require stack:
- repo\node_modules\@formatjs\cli\src\extract.js
- repo\node_modules\@formatjs\cli\index.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:939:15)
    at Module._load (node:internal/modules/cjs/loader:780:27)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (repo\node_modules\@formatjs\cli\src\extract.js:6:18)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Module._load (node:internal/modules/cjs/loader:827:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'repo\\node_modules\\@formatjs\\cli\\src\\extract.js',
    'repo\\node_modules\\@formatjs\\cli\\index.js'
  ]
}
```

### Codesandbox URL

Please include a codesandbox URL if possible

### Reproducible Steps/Repo

1. Create a `test.mjs` file
2. Paste in `import formatjs from '@formatjs/cli';`
3. Try to run it with `node ./test.mjs`

## Expected behavior

No import crash

## Desktop (please complete the following information):

- OS: [e.g. iOS] Win11
- Browser [e.g. chrome, safari] Node.js
- Version [e.g. 22] v18.2.0

## Additional context

No mention of `fs-extra` in the package.json:
https://github.com/formatjs/formatjs/blob/3e1aa52c32f93bc50efd46827f3c99e2bfac6d7b/packages/cli/package.json
I can find `fs-extra` imports at least here:
- https://github.com/formatjs/formatjs/blob/3e1aa52c32f93bc50efd46827f3c99e2bfac6d7b/packages/cli/src/compile.ts#L2
- https://github.com/formatjs/formatjs/blob/3e1aa52c32f93bc50efd46827f3c99e2bfac6d7b/packages/cli/src/compile_folder.ts#L3
- https://github.com/formatjs/formatjs/blob/3e1aa52c32f93bc50efd46827f3c99e2bfac6d7b/packages/cli/src/extract.ts#L2

**Comment by nstepien** [comment]
Not stale (that's an aggressive bot...)

**Comment by elado** [comment]
`@formatjs/cli` is missing many dependencies it accesses directly. It doesn't work with Yarn pnp.
I had to add the following to `.yarnrc.yml` to make it work:

```yml
packageExtensions:
  "@formatjs/cli@^5.0.2":
    dependencies:
      "tslib": "*"
      "chalk": "^4.0.0"
      "fs-extra": "^10.0.0"
      "@formatjs/ts-transformer": "^3.9.8"
      "@formatjs/icu-messageformat-parser": "^2.1.3"
      "json-stable-stringify": "^1.0.1"
      "typescript": "4.7.2"
```
